print ('Nama  ; Satria Tri Ferdiansyah')
print ('Nim   : 0110223039')
print ('Kelas : TI01')
print ('Alamat: jln pramuka raya 1 gang hasan')
print ('Teman')
print ('Nama  : Ryandra Athaya Saleh')
print ('Nim   : 0110223013')
print ('Kelas : TI01')
print ('Alamat: JL.Pakarena Raya no 6')
print (' Menjumlahkan 2 buah bilangan;',4+4)
print (' Mengurangi 2 buah bilangan',4-4)
print (' Mengalikan 2 buah bilangan',4*4)
print (' Membagi 2 buah bilangan',4//4)

